title: Hein's notes
description: Instead of saving my notes all over the place, have decided to move here (mainly technical stuff) for me, for everybody whenever needed. Alright, I'm gonna document properly.
theme: jekyll-theme-leap-day
