title: Hein's notes
description: Here are my notes mainly technical for me, for everybody whenever needed, instead of saving my notes all over the place. So, hopefully I documented properly.
theme: jekyll-theme-leap-day
